# Generated by Django 2.0.2 on 2018-02-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_auto_20180211_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='tags',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
